name: Build on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run MakeProject.bat
      run: .\MakeProject.bat

    - name: Build
      working-directory: build
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" HelloWorld.sln
      shell: cmd
